### ISSUE TITLE
Issue with saving

### ISSUE THREAD

**Issue by ulugeyik** [nicthib/pyanthem#1]
Very cool package and a method of visualization. 
I cannot save the video, I tried doing this:
"Finally, render output files with the Save --> Write A/V then merge menu command."

It does not show up. Choosing.  "Audio + Video" starts to create a file but then removes it saying "A/V only videos removed".

**Comment by nicthib** [comment]
That menu command is outdated - thanks for pointing this out, I need to update the README. If you want a video with audio merged, the correct option to choose is  "Audio + Video" so you're doing the right thing.

If you see the message "A/V only videos removed", the video with audio should be saved in the location of your original data file. Again, that message should be removed as it is more confusing than useful.

Can you check where you originally loaded your file to see if there is an .mp4 with "_AV.mp4" as the file suffix? If not, can you check your command prompt for any errors and paste them here?

**Comment by ulugeyik** [comment]
Thanks.  I was only paying attention to the GUI which did not indicate any errors. Looking at the command like told me that it could not find "fluidsynth", reinstalling that using "apt" instead of "pip" solved the problem.

**Comment by nicthib** [comment]
Great, glad it's working for you outside of the conda environment. I haven't had time to test that extensively. I'm going to close this for now, please let me know if you have any other issues!

I just updated pyanthem to version 1.2.9 to remove the confusing message about removing videos.
